version: "3.7"
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P123456p
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: clarusway_1
  networks:
    - clarusnet

  my-app:
    image: serdarcw/bookstore:latest:
    restart: always
    depends-on:
      - database:
    ports:
      - "80:80"
networks:
  - clarusnet:
     driver: bridge





    